### ISSUE TITLE
quoted_person field in the database

### ISSUE THREAD

**Issue by Murph33** [StemboltHQ/quoteboard#36]
Trying to decide on an implementation for the "quoted person" portion of the quoteboard.

EDIT: `quoted_person` is a string column that exists on each individual quote.  

Possible solution
1) hardcoded list of people (employees), the only accepted people as being quoted into the database.

Pros: Simple, can sort on a person's quotes (eg, give me top 5 Blackie quotes, Boxer) more easily, no risk of having Alex, Blackie, Alex Blackie all in the database.

Cons: Inflexible, will require upkeep when we want to add people to the quoteboard.

2) No list of people at all.

Pros: No upkeep in this regard required

Cons: Sorting on a user would be nearly impossible.  (Alex vs Blackie)

3) Accept someone that isn't in the list, but prefer someone in the list.  This is the system I would think would work the best.  I imagine most quotes will be added through slack (once that is a thing) and with
a list of employees somewhere we could implement some kind of fuzzy matching to auto complete the quoted person column.  If someone supplies a name that isn't in that list we can send a little message back asking them to confirm or not.  Likewise on the form on the webpage while there is an autocomplete box using select2 we can give the option to disable that box and fill a different field that would just accept any string.

pros: it does everything

cons: Still have a list that someone will need to be added to to work for sorting

I do understand it woudl be possible to query the DB to populate the select field but I could see that being worse and could more easily end up with several entries for one person.  Thoughts?  Opinions?

**Comment by jarednorman** [comment]
Put people in the database! Then they can be created if they don't exist.

**Comment by Murph33** [comment]
Ah sorry I wasn't very clear.

The "quoted_person" column is a string that exists on each individual quote.  It is not it's own table which possibly it should be.  At least I'm guessing that's what you assumed.

**Comment by jarednorman** [comment]
I understand. I'm saying it shouldn't be a string on each quote, that people should be a table in the database, and your quotes should have a quoted_person_id and the names should live in the people table.

**Comment by Murph33** [comment]
Yeah.  That definitely makes the most sense.  :+1:
